# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TallyFormCli < Formula
  desc "Markdown-to-Tally form builder"
  homepage "https://github.com/andinger/tally-form-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andinger/tally-form-cli/releases/download/v0.3.0/tally-form-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "75a7479b3b6167fafc11670479fcb310ffcb7ca0b019255d368d04dc39a7083b"

      define_method(:install) do
        bin.install "tally"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andinger/tally-form-cli/releases/download/v0.3.0/tally-form-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "2bde5aefd6981e05b2dc9a2450e725ff9a17896443f3703cdd9feb19b5be0939"

      define_method(:install) do
        bin.install "tally"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/tally-form-cli/releases/download/v0.3.0/tally-form-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "ba1f8622a78b75ecb0dd6a11db1a6b4ec1c9a8cf9fb5c4e089f82782f6b98676"
      define_method(:install) do
        bin.install "tally"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/tally-form-cli/releases/download/v0.3.0/tally-form-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "fdcf2be1d90a5f178d8da2118576fccc0ae793491c84061c4378df4e42637ed2"
      define_method(:install) do
        bin.install "tally"
      end
    end
  end

  test do
    system bin/"tally", "--version"
  end
end
