# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tally < Formula
  desc "Markdown-to-Tally form builder"
  homepage "https://github.com/andinger/tally-form-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andinger/tally-form-cli/releases/download/v1.0.3/tally-form-cli_1.0.3_darwin_amd64.tar.gz"
      sha256 "9bd0da7ea495f02f1dbf7346074ae5c6165a62c6cb357e490c44e6743dbd57b9"

      define_method(:install) do
        bin.install "tally"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andinger/tally-form-cli/releases/download/v1.0.3/tally-form-cli_1.0.3_darwin_arm64.tar.gz"
      sha256 "89d6f170ed6c39e602679e15a6780be4d235d9cd78bb943800ce055c12a1e74d"

      define_method(:install) do
        bin.install "tally"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/tally-form-cli/releases/download/v1.0.3/tally-form-cli_1.0.3_linux_amd64.tar.gz"
      sha256 "f73a4c9722fc2f1a5550223b825a66198bd29afb3e0e02164db15030acbb2914"
      define_method(:install) do
        bin.install "tally"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/tally-form-cli/releases/download/v1.0.3/tally-form-cli_1.0.3_linux_arm64.tar.gz"
      sha256 "b6f6386dbbb6d0dc35b52466c714a564bdcb6126f8dfd4809915c16d5bb09e73"
      define_method(:install) do
        bin.install "tally"
      end
    end
  end

  test do
    system bin/"tally", "--version"
  end
end
