# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tally < Formula
  desc "Markdown-to-Tally form builder"
  homepage "https://github.com/andinger/tally-form-cli"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andinger/tally-form-cli/releases/download/v1.4.0/tally-form-cli_1.4.0_darwin_amd64.tar.gz"
      sha256 "9d77db02b842667a0b265afecc63752417990be4968eabd8b92937b2acdcfa79"

      define_method(:install) do
        bin.install "tally"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andinger/tally-form-cli/releases/download/v1.4.0/tally-form-cli_1.4.0_darwin_arm64.tar.gz"
      sha256 "79e32aa0048edaeb373318037a44dcdee840d272d106530ce4161694d0fbd9ea"

      define_method(:install) do
        bin.install "tally"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/tally-form-cli/releases/download/v1.4.0/tally-form-cli_1.4.0_linux_amd64.tar.gz"
      sha256 "23db05742df5504a4594f9c3d42a65984c1c3e0804ae77aebb71772de29ac367"
      define_method(:install) do
        bin.install "tally"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/tally-form-cli/releases/download/v1.4.0/tally-form-cli_1.4.0_linux_arm64.tar.gz"
      sha256 "3f71a7f38291f9f2b300a300e5ca9a29a15047d3d2385549d147f31d088b3f2d"
      define_method(:install) do
        bin.install "tally"
      end
    end
  end

  test do
    system bin/"tally", "--version"
  end
end
