# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TallyFormCli < Formula
  desc "Markdown-to-Tally form builder"
  homepage "https://github.com/andinger/tally-form-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andinger/tally-form-cli/releases/download/v0.1.0/tally-form-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "95a2596f44a14eee16130522a4fb0719a1b05377e394eb9f32d993face0b9c52"

      define_method(:install) do
        bin.install "tally-form-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andinger/tally-form-cli/releases/download/v0.1.0/tally-form-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "79955a43802c8c17abf95f65cd9ba1e9994eeee867895595efc81e84dfd567bb"

      define_method(:install) do
        bin.install "tally-form-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/tally-form-cli/releases/download/v0.1.0/tally-form-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "2190c55da17e15f3a029e52430ec86fbbb34d1959edc6f577d4f4d01317f6708"
      define_method(:install) do
        bin.install "tally-form-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/tally-form-cli/releases/download/v0.1.0/tally-form-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "9577058de340ad8cf017c7fa423adb4404d72f9e425637f0cd021fff4a896fea"
      define_method(:install) do
        bin.install "tally-form-cli"
      end
    end
  end

  test do
    system bin/"tally-form-cli", "--version"
  end
end
