# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultquery < Formula
  desc "Query Obsidian vault files by YAML frontmatter"
  homepage "https://github.com/andinger/vaultquery"
  version "3.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andinger/vaultquery/releases/download/v3.2.0/vaultquery_3.2.0_darwin_amd64.tar.gz"
      sha256 "a3e202d09975f070c3642811a48292d3251a56a000274ad1976e5438fbfdbe03"

      define_method(:install) do
        bin.install "vaultquery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andinger/vaultquery/releases/download/v3.2.0/vaultquery_3.2.0_darwin_arm64.tar.gz"
      sha256 "e4050013c7043817865bb37d652da126e938dc2c650bfc70da03be3b0a684309"

      define_method(:install) do
        bin.install "vaultquery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/vaultquery/releases/download/v3.2.0/vaultquery_3.2.0_linux_amd64.tar.gz"
      sha256 "fb366a1953af44e7c7d87653792d216e2b3cf9e8788f97ade8cba2c471abe407"
      define_method(:install) do
        bin.install "vaultquery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/vaultquery/releases/download/v3.2.0/vaultquery_3.2.0_linux_arm64.tar.gz"
      sha256 "f817a9eed52d43c50390e866f0e83f356db3d91a1ee7fbf2ffdd156bf37aeea8"
      define_method(:install) do
        bin.install "vaultquery"
      end
    end
  end

  test do
    system bin/"vaultquery", "--version"
  end
end
