# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultquery < Formula
  desc "Query Obsidian vault files by YAML frontmatter"
  homepage "https://github.com/andinger/vaultquery"
  version "3.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andinger/vaultquery/releases/download/v3.1.4/vaultquery_3.1.4_darwin_amd64.tar.gz"
      sha256 "c18ed14f6fb3e34c621d0b4836284d142e86e46fe0f738483f19f04cca16dfc2"

      define_method(:install) do
        bin.install "vaultquery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andinger/vaultquery/releases/download/v3.1.4/vaultquery_3.1.4_darwin_arm64.tar.gz"
      sha256 "b825da4c87b5bc7c4777f63721679ea8dbb73b48c95c751fc3252c29239063fb"

      define_method(:install) do
        bin.install "vaultquery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/vaultquery/releases/download/v3.1.4/vaultquery_3.1.4_linux_amd64.tar.gz"
      sha256 "e695344250fc00bbca866f35ed84ab8072b558eb5a7ee5662b86f22a5715ed69"
      define_method(:install) do
        bin.install "vaultquery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/vaultquery/releases/download/v3.1.4/vaultquery_3.1.4_linux_arm64.tar.gz"
      sha256 "99408754d158ac4d2d2cea245f7f3223f890d2b942f8999446dca4b1f03c0c34"
      define_method(:install) do
        bin.install "vaultquery"
      end
    end
  end

  test do
    system bin/"vaultquery", "--version"
  end
end
